import { sheaBrand } from "@/lib/shea-content";
import type { PlatformSnapshot } from "@/lib/types";

export const platformSnapshot: PlatformSnapshot = {
  stores: [
    {
      id: "store_shea",
      name: "Shea Wellness LTD",
      slug: "shea-wellness",
      status: "active",
      platformDomain: "shea-wellness.myplatform.local",
      customDomain: null,
      currency: "KES",
      plan: "enterprise"
    }
  ],
  activeStore: {
    id: "store_shea",
    name: "Shea Wellness LTD",
    slug: "shea-wellness",
    status: "active",
    platformDomain: "shea-wellness.myplatform.local",
    customDomain: null,
    currency: "KES",
    plan: "enterprise"
  },
  metrics: [
    { label: "Gross sales", value: "KSh 48.6M", detail: "+18.4% from retail, spa, and distributor orders", trend: "up" },
    { label: "Orders", value: "12,248", detail: "218 retail and wholesale orders awaiting fulfillment", trend: "up" },
    { label: "Wholesale leads", value: "142", detail: "Retail partners, spas, and distributors in review", trend: "up" },
    { label: "Mobile sessions", value: "71%", detail: "Strong discovery from organic beauty shoppers", trend: "flat" }
  ],
  products: [
    {
      id: "prod_pure_raw",
      storeId: "store_shea",
      title: "Pure & Raw Shea Butter",
      description: "Unfragranced raw shea butter for body, face, and hair.",
      category: "Body Care",
      badge: "Pure & Raw",
      imageUrl: "/assets/sheawellness/pure-raw-shea-butter.jpeg",
      imagePosition: "50% 48%",
      rating: 4.9,
      reviewCount: 214,
      colors: ["Pure Raw"],
      sizes: ["100g", "250g", "500g"],
      material: "Raw Shea Butter",
      deliveryBadge: "Body, face and hair",
      price: 2000,
      inventoryQty: 156,
      status: "active",
      channel: "both",
      sales: 390
    },
    {
      id: "prod_lavender",
      storeId: "store_shea",
      title: "Lavender Shea Body Butter Infusion",
      description: "A calming shea butter infusion for dry, sensitive, and irritated skin.",
      category: "Body Care",
      badge: "Best seller",
      imageUrl: "/assets/sheawellness/lavender-shea-butter-front.jpeg",
      imagePosition: "50% 48%",
      rating: 4.9,
      reviewCount: 286,
      colors: ["Lavender", "Pure Raw", "Lemongrass", "Vanilla-Mint"],
      sizes: ["100g", "250g", "500g"],
      material: "Raw Shea Butter, Lavender Essential Oil, Vitamin E",
      deliveryBadge: "Calms irritated skin",
      price: 2400,
      inventoryQty: 148,
      status: "active",
      channel: "both",
      sales: 420
    },
    {
      id: "prod_lemongrass",
      storeId: "store_shea",
      title: "Lemongrass Shea Body Butter Infusion",
      description: "A fresh botanical butter for daily body and face moisture.",
      category: "Body Care",
      badge: "Fresh routine",
      imageUrl: "/assets/sheawellness/lemongrass-shea-butter-front.jpeg",
      imagePosition: "50% 50%",
      rating: 4.8,
      reviewCount: 177,
      colors: ["Lemongrass", "Lavender", "Grapefruit"],
      sizes: ["100g", "250g", "500g"],
      material: "Raw Shea Butter, Lemongrass Essential Oil, Vitamin E",
      deliveryBadge: "Daily glow",
      price: 2400,
      inventoryQty: 104,
      status: "active",
      channel: "both",
      sales: 318
    },
    {
      id: "prod_vanilla_mint",
      storeId: "store_shea",
      title: "Vanilla-Mint Shea Body Butter Infusion",
      description: "A cooling and comforting butter for body and face.",
      category: "Body Care",
      badge: "Comfort blend",
      imageUrl: "/assets/sheawellness/vanilla-mint-shea-butter.jpeg",
      imagePosition: "50% 52%",
      rating: 4.8,
      reviewCount: 144,
      colors: ["Vanilla-Mint", "Pure Raw", "Grapefruit"],
      sizes: ["100g", "250g", "500g"],
      material: "Raw Shea Butter, Vanilla, Mint Oil, Vitamin E",
      deliveryBadge: "Soft skin finish",
      price: 2400,
      inventoryQty: 91,
      status: "active",
      channel: "both",
      sales: 276
    },
    {
      id: "prod_grapefruit",
      storeId: "store_shea",
      title: "Grapefruit Shea Body Butter Infusion",
      description: "A bright citrus butter for body and face care.",
      category: "Body Care",
      badge: "Citrus glow",
      imageUrl: "/assets/sheawellness/grapefruit-shea-butter-front.jpeg",
      imagePosition: "50% 50%",
      rating: 4.7,
      reviewCount: 121,
      colors: ["Grapefruit", "Lavender", "Lemongrass"],
      sizes: ["100g", "250g", "500g"],
      material: "Raw Shea Butter, Grapefruit Essential Oil, Vitamin E",
      deliveryBadge: "Bright citrus scent",
      price: 2400,
      inventoryQty: 83,
      status: "active",
      channel: "both",
      sales: 250
    },
    {
      id: "prod_black_soap",
      storeId: "store_shea",
      title: "African Liquid Black Soap Body & Face Wash",
      description: "Gentle daily cleanser for face and body that removes impurities without a stripped feeling.",
      category: "Face Care",
      badge: "Handmade",
      imageUrl: "/assets/WhatsApp Image 2026-07-08 at 12.44.27 (3).jpeg",
      imagePosition: "50% 50%",
      rating: 4.8,
      reviewCount: 174,
      colors: ["Original", "Lavender & Clove", "Body Wash"],
      sizes: ["150ml", "300ml", "500ml", "Spa refill"],
      material: "African Black Soap, Shea Butter, Botanical Extracts",
      deliveryBadge: "Gentle daily cleanse",
      price: 1800,
      inventoryQty: 96,
      status: "active",
      channel: "both",
      sales: 335
    },
    {
      id: "prod_rosehip_facial_oil",
      storeId: "store_shea",
      title: "Rosehip Facial Oil",
      description: "Lightweight botanical oil that hydrates, softens, and supports a healthy-looking glow.",
      category: "Face Care",
      badge: "Face routine",
      imageUrl: "/assets/sheawellness/face-care-routine.png",
      imagePosition: "50% 50%",
      rating: 4.8,
      reviewCount: 67,
      colors: ["Rosehip", "Facial Oil"],
      sizes: ["50ml", "100ml"],
      material: "Rosehip Oil, Botanical Oil Blend",
      deliveryBadge: "2-4 drops daily",
      price: 2100,
      inventoryQty: 82,
      status: "active",
      channel: "both",
      sales: 129
    },
    {
      id: "prod_cucumber_mint_sunscreen",
      storeId: "store_shea",
      title: "Cucumber Mint Sunscreen SPF Gel",
      description: "Daily SPF gel for the final morning step of the Shea Wellness face care routine.",
      category: "Face Care",
      badge: "Protect",
      imageUrl: "/assets/sheawellness/face-care-routine.png",
      imagePosition: "50% 50%",
      rating: 4.7,
      reviewCount: 41,
      colors: ["Cucumber Mint", "SPF 20+"],
      sizes: ["50ml"],
      material: "Cucumber, Mint, Broad-spectrum SPF",
      deliveryBadge: "Morning protection",
      price: 1900,
      inventoryQty: 58,
      status: "active",
      channel: "both",
      sales: 94
    },
    {
      id: "prod_chebe_serum",
      storeId: "store_shea",
      title: "Chebe Hair Growth Serum with Karkar Oil",
      description: "A nourishing serum for protective styles, length retention, and scalp care.",
      category: "Hair Care",
      badge: "Hair growth",
      imageUrl: "/assets/shea-chebe-haircare.png",
      imagePosition: "50% 50%",
      rating: 4.7,
      reviewCount: 132,
      colors: ["Chebe Serum", "Chebe Butter", "Growth Duo"],
      sizes: ["50ml", "100ml", "Duo kit"],
      material: "Chebe Powder, Karkar Oil, Natural Oils",
      deliveryBadge: "Length retention",
      price: 2200,
      inventoryQty: 64,
      status: "low_stock",
      channel: "both",
      sales: 261
    },
    {
      id: "prod_chebe_butter",
      storeId: "store_shea",
      title: "Chebe Hair Butter",
      description: "Rich hair butter for nourishment, shine, and breakage prevention.",
      category: "Hair Care",
      badge: "Breakage care",
      imageUrl: "/assets/shea-chebe-haircare.png",
      imagePosition: "50% 50%",
      rating: 4.8,
      reviewCount: 116,
      colors: ["Chebe Butter", "Growth Duo"],
      sizes: ["100g", "250g"],
      material: "Shea Butter, Chebe, Natural Oils",
      deliveryBadge: "Shine and nourishment",
      price: 2100,
      inventoryQty: 78,
      status: "active",
      channel: "both",
      sales: 224
    },
    {
      id: "prod_yellow_castor_oil",
      storeId: "store_shea",
      title: "Cold Pressed Yellow Castor Oil",
      description: "Rich castor oil for dry scalp, brittle hair, protective styles, and body moisture sealing.",
      category: "Hair Care",
      badge: "Scalp moisture",
      imageUrl: "/assets/sheawellness/face-care-routine.png",
      imagePosition: "50% 50%",
      rating: 4.8,
      reviewCount: 73,
      colors: ["Yellow Castor Oil"],
      sizes: ["100ml", "250ml"],
      material: "Cold Pressed Yellow Castor Oil",
      deliveryBadge: "Hair and body moisture",
      price: 1700,
      inventoryQty: 68,
      status: "active",
      channel: "both",
      sales: 138
    },
    {
      id: "prod_essential_oils",
      storeId: "store_shea",
      title: "Essential Oils & Wellness Kit",
      description: "Lavender, lemongrass, tea tree, eucalyptus, peppermint, rosemary, sweet orange, and vanilla oils.",
      category: "Essential Oils",
      badge: "Wellness routine",
      imageUrl: "/assets/shea-essential-oils.png",
      imagePosition: "50% 50%",
      rating: 4.8,
      reviewCount: 118,
      colors: ["Lavender", "Lemongrass", "Tea Tree", "Peppermint"],
      sizes: ["Single oil", "6-oil set", "Wholesale pack"],
      material: "Pure essential oils",
      deliveryBadge: "Sleep and focus",
      price: 3200,
      inventoryQty: 73,
      status: "active",
      channel: "online",
      sales: 198
    },
    {
      id: "prod_aromatherapy",
      storeId: "store_shea",
      title: "Aromatherapy Humidifier Bundle",
      description: "A diffuser-ready wellness bundle for essential oil routines.",
      category: "Aromatherapy",
      badge: "Spa ambience",
      imageUrl: "/assets/shea-essential-oils.png",
      imagePosition: "50% 50%",
      rating: 4.7,
      reviewCount: 74,
      colors: ["White", "Natural", "Spa bundle"],
      sizes: ["Single unit", "Spa bundle"],
      material: "Aromatherapy humidifier with essential oil compatibility",
      deliveryBadge: "Relaxation setup",
      price: 4200,
      inventoryQty: 38,
      status: "active",
      channel: "online",
      sales: 142
    },
    {
      id: "prod_spa_essentials",
      storeId: "store_shea",
      title: "Professional Spa Essentials Kit",
      description: "Export-ready spa supplies including massage oils, bed sheets, disposable wear, and salon equipment.",
      category: "Spa Essentials",
      badge: "Wholesale ready",
      imageUrl: "/assets/shea-hero.png",
      imagePosition: "50% 50%",
      rating: 4.9,
      reviewCount: 94,
      colors: ["Massage Oil", "Bed Sheets", "Disposable Wear", "Salon Kit"],
      sizes: ["Starter", "Salon", "Distributor"],
      material: "Massage oils, disposable massage bed sheets, disposable pants and bras, salon equipment",
      deliveryBadge: "Export packaging",
      price: 4800,
      inventoryQty: 52,
      status: "active",
      channel: "both",
      sales: 176
    },
    {
      id: "prod_gift_set",
      storeId: "store_shea",
      title: "Shea Wellness Gift Set",
      description: "A curated body butter, black soap, and essential oil set for self-care gifting.",
      category: "Gift Sets",
      badge: "Gift-ready",
      imageUrl: "/assets/sheawellness/grapefruit-shea-butter-lid.jpeg",
      imagePosition: "50% 48%",
      rating: 4.9,
      reviewCount: 88,
      colors: ["Glow Set", "Calm Set", "Corporate Set"],
      sizes: ["Mini set", "Signature set", "Corporate pack"],
      material: "Shea Body Butter, African Black Soap, Essential Oil",
      deliveryBadge: "Retail bundle",
      price: 5800,
      inventoryQty: 46,
      status: "active",
      channel: "both",
      sales: 154
    },
    {
      id: "prod_distributor_offer",
      storeId: "store_shea",
      title: "Distributor Starter Offer",
      description: "A wholesale-friendly introduction to Shea Wellness best sellers.",
      category: "Offers",
      badge: "Retail partner",
      imageUrl: "/assets/sheawellness/lavender-shea-butter-lid.jpeg",
      imagePosition: "50% 50%",
      rating: 4.8,
      reviewCount: 52,
      colors: ["Starter", "Growth", "Distributor"],
      sizes: ["Starter", "Growth", "Distributor"],
      material: "Assorted Shea Wellness products",
      deliveryBadge: "Catalogue request",
      price: 12000,
      inventoryQty: 25,
      status: "active",
      channel: "both",
      sales: 86
    }
  ],
  orders: [
    {
      id: "ord_1089",
      storeId: "store_shea",
      orderNumber: "#1089",
      customerName: "Amina Mwangi",
      totalPrice: 13200,
      paymentStatus: "paid",
      fulfillmentStatus: "unfulfilled",
      placedAt: "2026-06-24T07:42:00.000Z"
    },
    {
      id: "ord_1088",
      storeId: "store_shea",
      orderNumber: "#1088",
      customerName: "Nia Wellness Spa",
      totalPrice: 38400,
      paymentStatus: "paid",
      fulfillmentStatus: "partial",
      placedAt: "2026-06-24T06:19:00.000Z"
    },
    {
      id: "ord_1087",
      storeId: "store_shea",
      orderNumber: "#1087",
      customerName: "Organic Beauty Store",
      totalPrice: 52400,
      paymentStatus: "pending",
      fulfillmentStatus: "on_hold",
      placedAt: "2026-06-23T18:06:00.000Z"
    }
  ],
  customers: [
    {
      id: "cust_amina",
      storeId: "store_shea",
      name: "Amina Mwangi",
      email: "amina@example.com",
      lifetimeValue: 2840,
      orders: 18,
      segment: "VIP"
    },
    {
      id: "cust_spa",
      storeId: "store_shea",
      name: "Nia Wellness Spa",
      email: "orders@niawellness.example",
      lifetimeValue: 6120,
      orders: 24,
      segment: "Wholesale spa"
    },
    {
      id: "cust_beauty",
      storeId: "store_shea",
      name: "Organic Beauty Store",
      email: "buyer@organicbeauty.example",
      lifetimeValue: 4980,
      orders: 15,
      segment: "Distributor"
    }
  ],
  theme: {
    version: 1,
    sections: [
      {
        type: "header",
        settings: {
          brand: sheaBrand.name,
          nav: ["Body Care", "Face Care", "Hair Care", "Wholesale"],
          announcement: sheaBrand.promises.join(" | ")
        }
      },
      {
        type: "hero",
        settings: {
          headline: sheaBrand.headline,
          body: sheaBrand.summary,
          cta: "Shop Products",
          secondaryCta: "Become a Distributor",
          mediaUrl: "/assets/sheawellness/lavender-shea-butter-front.jpeg",
          imageTone: "evergreen"
        }
      },
      {
        type: "category_rail",
        settings: {
          title: "Shop Shea Wellness routines",
          categories: [
            { label: "Body Care", detail: "Pure & Raw, Lavender, Lemongrass, Vanilla-Mint, Grapefruit" },
            { label: "Face Care", detail: "African liquid black soap for gentle detox" },
            { label: "Hair Care", detail: "Chebe serum, Chebe butter, and black soap shampoo" },
            { label: "Essential Oils", detail: "Lavender, lemongrass, tea tree, eucalyptus, peppermint, rosemary, sweet orange, vanilla" },
            { label: "Spa Essentials", detail: "Massage oils, disposables, and professional salon equipment" }
          ]
        }
      },
      {
        type: "featured_collection",
        settings: {
          title: "Premium handcrafted wellness",
          subtitle: "Natural, ethical, and export-ready skincare for shoppers, spas, and distributors.",
          productIds: ["prod_pure_raw", "prod_lavender", "prod_lemongrass", "prod_black_soap", "prod_chebe_serum"]
        }
      },
      {
        type: "editorial_split",
        settings: {
          kicker: "Sustainability",
          title: "Ethically sourced from African women cooperatives.",
          body: "Shea Wellness blends clean formulations with African heritage, eco-conscious packaging, and community-first sourcing.",
          points: ["Paraben-free and sulfate-free formulas", "100% organic product positioning", "Private label and wholesale-ready packaging"]
        }
      },
      {
        type: "trust_bar",
        settings: {
          items: sheaBrand.promises
        }
      },
      {
        type: "footer",
        settings: {
          text: `${sheaBrand.name} - ${sheaBrand.address}. ${sheaBrand.email} | ${sheaBrand.phone}`
        }
      }
    ]
  }
};
