import { ArrowRight, CheckCircle2 } from "lucide-react";
import { SheaCommerceFooter, SheaTrustGrid, SheaWhatsApp } from "@/components/storefront/SheaCommerceChrome";
import { SheaGlobalHeader } from "@/components/storefront/SheaGlobalHeader";

const content = {
  policies: { eyebrow: "Customer care", title: "Clear, fair shopping policies.", intro: "We want every Shea Wellness order to feel simple and transparent.", sections: [["Purchases", "Product availability, pricing, and delivery estimates are confirmed during checkout."], ["Product care", "Store natural products in a cool, dry place and follow the directions supplied with each item."], ["Support", "Contact us promptly if an order arrives damaged, incomplete, or different from what you ordered."]] },
  refund: { eyebrow: "Refund policy", title: "Shop confidently with straightforward support.", intro: "If there is a problem with your order, contact our team so we can assess and resolve it fairly.", sections: [["Eligible concerns", "Report damaged, incorrect, or defective products with your order details and clear photographs."], ["Hygiene and safety", "Opened personal-care products cannot normally be returned unless they are defective."], ["Resolution", "Approved cases may receive a replacement, store credit, or refund through the original payment method."]] },
  shipping: { eyebrow: "Shipping information", title: "Reliable delivery from Nairobi to your door.", intro: "Shipping costs and delivery estimates are shown during checkout and depend on destination and order size.", sections: [["Kenya delivery", "Orders are prepared carefully and dispatched through suitable local delivery partners."], ["International and wholesale", "Export and bulk orders receive a tailored quotation, documentation, and fulfilment timeline."], ["Order support", "Tracking or delivery updates are shared using the contact details supplied at checkout."]] },
  faq: { eyebrow: "Frequently asked questions", title: "Helpful answers before you order.", intro: "Still unsure? Chat with the Shea Wellness team for product and routine guidance.", sections: [["Are the products natural?", "Our range is built around shea butter, botanical oils, essential oils, and nature-led formulations."], ["Can I use these products on sensitive skin?", "Patch-test first and introduce one product at a time. Stop use if irritation occurs."], ["Do you accept M-Pesa?", "Yes. M-Pesa is supported alongside the payment methods presented during checkout."], ["Do you supply wholesale?", "Yes. Retailers, spas, hotels, wellness centres, and distributors can request wholesale support."]] }
} as const;

export function SheaPolicyPage({ kind }: { kind: keyof typeof content }) {
  const page = content[kind];
  return <main className="shea-policy-page"><SheaGlobalHeader /><section className="shea-policy-hero"><span>{page.eyebrow}</span><h1>{page.title}</h1><p>{page.intro}</p><a href="/contact">Contact our team <ArrowRight size={17} /></a></section><section className="shea-policy-cards">{page.sections.map(([title, body]) => <article key={title}><CheckCircle2 size={20} /><h2>{title}</h2><p>{body}</p></article>)}</section><SheaTrustGrid /><SheaCommerceFooter /><SheaWhatsApp /></main>;
}
